Changes(helpers.py,modal_cobro.tsx,product_detail.tsx,.gitignore): gi…
miligon/BusinessCaptain pull request #3
Opened 2024-05-18 16:41 UTC by PJDev1

…tig added .DS_STORE, rm: ticketfolio, modal_cobro payment modals, add barcode validation

2024-05-18 17:36 UTC, miligon commented on frontend/pos/components/forms/modal_cobro.tsx
> +            <i className="ri-cash-line" />
porfa, cambia el icono a bank-card-fill

2024-05-18 17:42 UTC, miligon commented on frontend/pos/components/forms/modal_cobro.tsx
> +              <Input innerRef={inputRef} onKeyDown={(e) => handleKeyDownOnSearch(e.code)} value={montoConfirmado} onChange={(e) => setMontoConfirmado(parseFloat(e.target.value))} step={0.01} min={0}
Al intentar ingresar el monto, la casilla no lo permite: https://www.loom.com/share/92a9ea0a7d7646a3bdbffa38898070d9

2024-05-18 17:45 UTC, miligon requested changes
Porfa checa los comentarios de la parte del modal de cobro

2024-05-20 01:56 UTC, PJDev1 commented on frontend/pos/components/forms/modal_cobro.tsx
> +              <Input innerRef={inputRef} onKeyDown={(e) => handleKeyDownOnSearch(e.code)} value={montoConfirmado} onChange={(e) => setMontoConfirmado(parseFloat(e.target.value))} step={0.01} min={0}
Ya se arregló ese detalle.

2024-05-20 01:57 UTC, PJDev1 commented on frontend/pos/components/forms/modal_cobro.tsx
> +            <i className="ri-cash-line" />
Ya se cambio el icono.

2024-05-20 17:10 UTC, miligon approved these changes

2024-05-20 17:11 UTC, merged